// src/types/api.ts
// AUTO-GENERATED by `npm run sync-api-types` from /api/v1/openapi.json — never edit manually
// This file is kept in sync via the postinstall script defined in package.json
export type { /* All types from OpenAPI spec */ } from "./generated";