# Generated by Django 5.1.4 on 2026-04-13 06:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed above the tool grid.')),
            ],
            options={
                'verbose_name': 'Tools directory',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ToolDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('health', 'Health & Fitness'), ('scientific', 'Scientific'), ('productivity', 'Productivity'), ('other', 'Other')], db_index=True, default='other', help_text='Tool category — used for /tools/{category}/ routing in Next.js.', max_length=30)),
                ('calculator_slug', models.SlugField(help_text="Machine-readable identifier linking this page to its React component and backend compute function (e.g. 'compound-interest'). Must exactly match a key in CALCULATOR_REGISTRY in apps/tools/views.py.", unique=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name displayed on tool cards (e.g. 'calculator', 'heart-pulse'). Browse available icons at https://lucide.dev/icons/", max_length=50)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured tools appear prominently on the /tools/ homepage grid.')),
                ('body', wagtail.fields.StreamField([('intro', 0), ('formula_block', 4), ('use_cases', 8), ('faq', 12), ('image', 13), ('paragraph', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Tool introduction (two to four paragraphs). Appears above the calculator widget.', 'label': 'Introduction'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Brief label for the formula (e.g. 'Compound Interest Formula')."}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Formula in LaTeX (e.g. A = P(1 + r/n)^{nt}) or plain text. The Next.js renderer uses KaTeX if LaTeX delimiters are detected.'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Plain-language explanation of the formula and its variables.'}), 4: ('wagtail.blocks.StructBlock', [[('title', 1), ('formula', 2), ('explanation', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Use-case headline (e.g. 'Retirement Planning')."}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Two to three sentences describing this use case.'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'List of real-world scenarios where this calculator is useful.', 'label': 'Use cases'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "FAQ question (sentence case, ends with '?')."}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Concise answer. Aim for two to four sentences.'}), 11: ('wagtail.blocks.StructBlock', [[('question', 9), ('answer', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Frequently asked questions about this calculator. Rendered as schema.org FAQPage.', 'label': 'FAQ'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Rich text paragraph'})})),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image for the tool detail page (served at 800×400).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Calculator tool',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
