# Generated by Django 5.1.4 on 2026-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tooldetailpage_canonical_url_tooldetailpage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldetailpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='tooldetailpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='tooldetailpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
        migrations.AddField(
            model_name='toolindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='toolindexpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='toolindexpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
    ]
