version: '3.8'

services:
  portfolio-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "80:80"      # Frontend via nginx
      - "8000:8000"  # Backend API (optional direct access)
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-production-key-change-this-in-production
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=lms_backend.settings
      - PYTHONPATH=/app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/var/log/supervisor
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  logs_volume: