# Generated by Django 5.1.4 on 2026-04-13 06:26

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or deck text displayed below the headline.', max_length=250)),
                ('reading_time', models.PositiveSmallIntegerField(default=5, help_text='Estimated reading time in minutes (displayed in the post header).')),
                ('category', models.CharField(blank=True, db_index=True, help_text="Primary category slug (e.g. 'python', 'devops'). Used for /blog/category/ routing.", max_length=100)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('code', 5), ('callout', 8), ('embed', 9), ('raw_html', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading (renders as <h2> in Next.js).', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'code'], 'help_text': 'Rich text paragraph block.'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'python', 'help_text': 'Programming language identifier used for syntax highlighting (e.g. python, typescript, bash, sql).'}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste raw source code. Do NOT manually HTML-escape — the renderer handles this.'}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'ℹ Info'), ('warning', '⚠ Warning'), ('tip', '💡 Tip')], 'help_text': "Visual variant — controls the callout's colour and icon."}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Callout body text. Keep concise — one to three sentences.'}), 8: ('wagtail.blocks.StructBlock', [[('type', 6), ('text', 7)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo, or Twitter URL to embed.', 'icon': 'media'}), 10: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '⚠ Use sparingly. Raw HTML is injected unescaped into the page. Ensure content is sanitised before saving.', 'icon': 'code', 'label': 'Raw HTML'})})),
                ('hero_image', models.ForeignKey(blank=True, help_text='Main hero image. Served in two renditions: thumbnail (800×400) and OG (1200×630).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog post',
                'ordering': ['-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short introduction displayed above the post listing.')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero banner image for the blog index page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogdetailpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Comma-separated tags for discovery and related posts.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Comma-separated tags for discovery and related posts.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
