# Generated by Django 5.1.4 on 2026-04-13 13:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetailpage_canonical_url_blogdetailpage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagetag',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('code', 8), ('callout', 11), ('embed', 12), ('raw_html', 13)], blank=True, block_lookup={0: ('apps.blog.models.ValidatedHeadingBlock', (), {'form_classname': 'title', 'help_text': 'Section heading (renders as <h2> in Next.js).', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'code'], 'help_text': 'Rich text paragraph block.'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image for this section.'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Alternative text for the image. Auto-fills from the focus keyword if left blank.', 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional caption for editors and SEO context.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'python', 'help_text': 'Programming language identifier used for syntax highlighting (e.g. python, typescript, bash, sql).'}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste raw source code. Do NOT manually HTML-escape — the renderer handles this.'}), 8: ('wagtail.blocks.StructBlock', [[('language', 6), ('code', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'ℹ Info'), ('warning', '⚠ Warning'), ('tip', '💡 Tip')], 'help_text': "Visual variant — controls the callout's colour and icon."}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Callout body text. Keep concise — one to three sentences.'}), 11: ('wagtail.blocks.StructBlock', [[('type', 9), ('text', 10)]], {}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo, or Twitter URL to embed.', 'icon': 'media'}), 13: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '⚠ Use sparingly. Raw HTML is injected unescaped into the page. Ensure content is sanitised before saving.', 'icon': 'code', 'label': 'Raw HTML'})}),
        ),
    ]
