# Generated by Django 5.2.6 on 2025-09-08 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("content_view", "Content View"),
                            ("user_action", "User Action"),
                            ("api_call", "API Call"),
                            ("error", "Error"),
                            ("performance", "Performance"),
                        ],
                        help_text="Type of event being logged",
                        max_length=50,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        help_text="Specific name of the event", max_length=100
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data in JSON format",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event occurred",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session identifier for tracking user sessions",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from the browser"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event (null for anonymous users)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="events_even_event_t_7f62e2_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="events_even_user_id_2856a0_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="events_even_timesta_f13b35_idx"
                    ),
                ],
            },
        ),
    ]
