# Generated by Django 5.2.6 on 2025-09-07 14:56

import django.core.validators
import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("og_image", models.ImageField(blank=True, upload_to="og_images/")),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                ("secondary_keywords", models.TextField(blank=True)),
                (
                    "readability_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "seo_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("social_media_title", models.CharField(blank=True, max_length=60)),
                (
                    "social_media_description",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary with Large Image"),
                        ],
                        default="summary",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Default Template"),
                            ("landing", "Landing Page"),
                            ("about", "About Page"),
                            ("contact", "Contact Page"),
                            ("portfolio", "Portfolio Page"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                ("page_order", models.IntegerField(default=0)),
                ("is_homepage", models.BooleanField(default=False)),
                ("show_in_menu", models.BooleanField(default=True)),
                ("menu_title", models.CharField(blank=True, max_length=50)),
                ("custom_css", models.TextField(blank=True)),
                ("custom_js", models.TextField(blank=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "ordering": ["page_order", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_homepage", True)),
                        fields=("is_homepage",),
                        name="unique_homepage",
                    )
                ],
            },
        ),
    ]
