# Generated by Django 5.1.4 on 2026-04-13 06:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('team_member', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading (renders as <h2>).', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Rich text paragraph.'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Full name of team member'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title / role'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short bio (2–4 sentences)'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Portrait photo (recommended 400×400)'}), 7: ('wagtail.blocks.StructBlock', [[('name', 3), ('role', 4), ('bio', 5), ('photo', 6)]], {})}, help_text='Main page content blocks.')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text above the contact details.')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email address.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number with country code if needed.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address or mailing address.')),
                ('show_contact_form', models.BooleanField(default=True, help_text='Whether to display the contact form on the frontend.')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(help_text='Main headline displayed in the hero banner.', max_length=120)),
                ('hero_subheading', models.CharField(blank=True, help_text='Supporting subheadline (optional).', max_length=250)),
                ('hero_cta_text', models.CharField(blank=True, help_text="Call-to-action button text (e.g. 'Explore Tools').", max_length=40)),
                ('hero_cta_url', models.CharField(blank=True, help_text='Internal or external URL for the CTA button.', max_length=200)),
                ('intro_body', wagtail.fields.RichTextField(blank=True, help_text='Short introduction text shown below the hero.')),
                ('featured_tools_heading', models.CharField(blank=True, default='Featured Calculators', help_text='Heading for the featured tools grid on homepage.', max_length=100)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Large hero background image (1920×1080 recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
