# Generated by Django 5.1.4 on 2026-04-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutpage_canonical_url_aboutpage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary SEO focus keyword for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_prompt_suggestion',
            field=models.TextField(blank=True, help_text='Suggested prompt for featured image generation or caption guidance.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_excerpt',
            field=models.TextField(blank=True, help_text='Short SEO excerpt for search snippets and editorial guidance.', max_length=300),
        ),
    ]
