/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["api_v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["api_v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_blog_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve a single published post by slug (API endpoint). */
        get: operations["api_v1_blog_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/{slug}/related/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List up to 3 related posts based on shared category or tags (API endpoint). */
        get: operations["api_v1_blog_related_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Simple read-only endpoint that returns both courses and tools.
         *
         *     This matches the frontend expectation of a single
         *     `/api/knowledge/` payload containing the two collections.  It keeps the
         *     existing individual `/courses/` and `/tools/` endpoints for more granular
         *     access or future pagination.
         */
        get: operations["api_v1_knowledge_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_knowledge_courses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/courses/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_knowledge_courses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/resources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_knowledge_resources_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/tools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_knowledge_tools_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all projects with filtering and pagination.  Staff users can also
         *     create new project entries via POST (admin-only permission enforced).
         */
        get: operations["api_v1_projects_list"];
        put?: never;
        /**
         * @description List all projects with filtering and pagination.  Staff users can also
         *     create new project entries via POST (admin-only permission enforced).
         */
        post: operations["api_v1_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve, update or delete a project by slug.  Modify operations require
         *     admin privileges (handled by IsAdminOrReadOnly permission class).
         */
        get: operations["api_v1_projects_retrieve"];
        /**
         * @description Retrieve, update or delete a project by slug.  Modify operations require
         *     admin privileges (handled by IsAdminOrReadOnly permission class).
         */
        put: operations["api_v1_projects_update"];
        post?: never;
        /**
         * @description Retrieve, update or delete a project by slug.  Modify operations require
         *     admin privileges (handled by IsAdminOrReadOnly permission class).
         */
        delete: operations["api_v1_projects_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Retrieve, update or delete a project by slug.  Modify operations require
         *     admin privileges (handled by IsAdminOrReadOnly permission class).
         */
        patch: operations["api_v1_projects_partial_update"];
        trace?: never;
    };
    "/api/v1/resume/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only endpoint that aggregates all resume sections into a single payload. */
        get: operations["api_v1_resume_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for the Category model (read‑only). */
        Category: {
            readonly id: number;
            name: string;
            slug?: string;
            description?: string;
        };
        Certification: {
            readonly id: number;
            readonly name: string;
            readonly issuing_organization: string;
            /** Format: date */
            readonly issue_date: string;
            /** Format: date */
            readonly expiration_date: string | null;
            readonly credential_id: string;
            /**
             * Verification URL
             * Format: uri
             */
            readonly credential_url: string;
            readonly order: number;
        };
        Contact: {
            name: string;
            /** Format: email */
            email: string;
            subject: string;
            message: string;
            /** @description Hidden field for bot detection */
            honeypot?: string;
        };
        CourseDetail: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly description: string;
            readonly difficulty: components["schemas"]["DifficultyEnum"];
            /** @description Approximate time to complete */
            readonly estimated_hours: number;
            readonly featured: boolean;
            readonly meta_title: string;
            readonly meta_desc: string;
            readonly lessons: components["schemas"]["Lesson"][];
        };
        CourseList: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly difficulty: components["schemas"]["DifficultyEnum"];
            /** @description Approximate time to complete */
            readonly estimated_hours: number;
            readonly featured: boolean;
            readonly lesson_count: string;
        };
        /**
         * @description * `beginner` - Beginner
         *     * `intermediate` - Intermediate
         *     * `advanced` - Advanced
         * @enum {string}
         */
        DifficultyEnum: "beginner" | "intermediate" | "advanced";
        Education: {
            readonly id: number;
            readonly degree: string;
            readonly institution: string;
            readonly location: string;
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string | null;
            /** @description Additional details (honors, thesis, etc.) */
            readonly description: string;
            readonly order: number;
        };
        Experience: {
            readonly id: number;
            readonly title: string;
            readonly company: string;
            readonly location: string;
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string | null;
            /** @description Currently working here */
            readonly current: boolean;
            readonly description: string;
            /** @description Key accomplishments (bullet points) */
            readonly achievements: string;
            /** @description Display order (newest first) */
            readonly order: number;
        };
        /** @description Aggregate endpoint returning both courses and tools for a single payload. */
        Knowledge: {
            readonly courses: components["schemas"]["CourseList"][];
            readonly tools: components["schemas"]["Tool"][];
        };
        Lesson: {
            readonly id: number;
            readonly title: string;
            /** @description Lesson content (markdown or HTML) */
            readonly content: string;
            /**
             * Format: uri
             * @description Optional video URL
             */
            readonly video_url: string;
            readonly order: number;
        };
        PaginatedCourseListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CourseList"][];
        };
        PaginatedPostListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PostList"][];
        };
        PaginatedProjectListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectList"][];
        };
        PaginatedResourceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Resource"][];
        };
        PatchedProjectDetail: {
            readonly id?: number;
            title?: string;
            slug?: string;
            meta_desc?: string;
            readonly tagline?: string;
            readonly tags?: string[];
            readonly categories?: components["schemas"]["Category"][];
            readonly category?: string;
            year?: number | null;
            readonly thumbnail?: string;
            readonly image?: string;
            overview?: string;
            challenge?: string;
            solution?: string;
            role?: string;
            timeline?: string;
            /** Format: uri */
            live_url?: string;
            /** Format: uri */
            github_url?: string;
            /** Format: uri */
            readonly github?: string;
            /** Format: uri */
            readonly demo?: string;
            featured?: boolean;
            /** Format: date */
            completion_date?: string | null;
            /** Format: uri */
            featured_image?: string | null;
            readonly images?: components["schemas"]["ProjectImage"][];
        };
        /**
         * @description Detailed serializer for single post view (APIPostDetailView).
         *     Includes full content, all images, and SEO fields.
         */
        PostDetail: {
            readonly id: number;
            title: string;
            slug?: string;
            readonly author: components["schemas"]["User"];
            readonly category: components["schemas"]["Category"];
            readonly tags: components["schemas"]["Tag"][];
            /** @description Main post content (HTML sanitized on save) */
            content: string;
            /** @description Short summary for listings and SEO (auto-generated if blank). */
            excerpt?: string;
            /** Format: uri */
            featured_image?: string;
            /** Format: date-time */
            publish_date?: string;
            /** @description Mark as featured post */
            featured?: boolean;
            /** @description Estimated reading time in minutes (auto-calculated) */
            readonly read_time: number;
            readonly view_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            meta_title?: string;
            readonly meta_description: string;
            /** @description List of gallery images ordered by the 'order' field. */
            readonly images: components["schemas"]["PostImage"][];
        };
        /** @description Serializer for the PostImage model (gallery images). */
        PostImage: {
            readonly id: number;
            /** Format: uri */
            image: string;
            /** @description Optional caption text */
            caption?: string;
            /** @description Alternative text for accessibility */
            alt_text?: string;
            /** @description Display order (ascending) */
            order?: number;
        };
        /**
         * @description Lightweight serializer for list views (APIPostListView, APIRelatedPostsView).
         *     Includes nested author, category, tags, and a computed image count.
         */
        PostList: {
            readonly id: number;
            title: string;
            slug?: string;
            readonly author: components["schemas"]["User"];
            readonly category: components["schemas"]["Category"];
            readonly tags: components["schemas"]["Tag"][];
            /** @description Short summary for listings and SEO (auto-generated if blank). */
            excerpt?: string;
            /** Format: uri */
            featured_image?: string;
            /** Format: date-time */
            publish_date?: string;
            /** @description Mark as featured post */
            featured?: boolean;
            /** @description Estimated reading time in minutes (auto-calculated) */
            readonly read_time: number;
            readonly view_count: number;
            /** @description Number of additional images in the gallery. */
            readonly image_count: number;
        };
        /**
         * @description * `1` - Beginner
         *     * `2` - Elementary
         *     * `3` - Intermediate
         *     * `4` - Advanced
         *     * `5` - Expert
         * @enum {integer}
         */
        ProficiencyEnum: 1 | 2 | 3 | 4 | 5;
        ProjectDetail: {
            readonly id: number;
            title: string;
            slug?: string;
            meta_desc?: string;
            readonly tagline: string;
            readonly tags: string[];
            readonly categories: components["schemas"]["Category"][];
            readonly category: string;
            year?: number | null;
            readonly thumbnail: string;
            readonly image: string;
            overview?: string;
            challenge?: string;
            solution?: string;
            role?: string;
            timeline?: string;
            /** Format: uri */
            live_url?: string;
            /** Format: uri */
            github_url?: string;
            /** Format: uri */
            readonly github: string;
            /** Format: uri */
            readonly demo: string;
            featured?: boolean;
            /** Format: date */
            completion_date?: string | null;
            /** Format: uri */
            featured_image?: string | null;
            readonly images: components["schemas"]["ProjectImage"][];
        };
        ProjectImage: {
            /** Format: uri */
            image: string;
        };
        ProjectList: {
            readonly id: number;
            title: string;
            slug?: string;
            meta_desc?: string;
            readonly tagline: string;
            readonly tags: string[];
            readonly categories: components["schemas"]["Category"][];
            readonly category: string;
            year?: number | null;
            readonly thumbnail: string;
            readonly image: string;
            featured?: boolean;
            /** Format: date */
            completion_date?: string | null;
            /** Format: uri */
            featured_image?: string | null;
            /** Format: uri */
            readonly github: string;
            /** Format: uri */
            readonly demo: string;
        };
        Resource: {
            readonly id: number;
            readonly title: string;
            /** Format: uri */
            readonly url: string;
            readonly description: string;
            readonly resource_type: components["schemas"]["ResourceTypeEnum"];
            /** @description Comma-separated tags */
            readonly tags: string;
            readonly order: number;
        };
        /**
         * @description * `article` - Article
         *     * `video` - Video
         *     * `book` - Book
         *     * `course` - Course
         *     * `tool` - Tool
         * @enum {string}
         */
        ResourceTypeEnum: "article" | "video" | "book" | "course" | "tool";
        Resume: {
            readonly skills: components["schemas"]["SkillCategory"][];
            readonly experience: components["schemas"]["Experience"][];
            readonly education: components["schemas"]["Education"][];
            readonly certifications: components["schemas"]["Certification"][];
        };
        Skill: {
            readonly id: number;
            readonly name: string;
            /**
             * @description Self-rated proficiency level
             *
             *     * `1` - Beginner
             *     * `2` - Elementary
             *     * `3` - Intermediate
             *     * `4` - Advanced
             *     * `5` - Expert
             */
            readonly proficiency: components["schemas"]["ProficiencyEnum"];
            /** @description Icon class name (e.g., Font Awesome) */
            readonly icon: string;
            readonly order: number;
        };
        SkillCategory: {
            readonly id: number;
            readonly name: string;
            readonly description: string;
            /** @description Display order */
            readonly order: number;
            readonly skills: components["schemas"]["Skill"][];
        };
        /** @description Serializer for the Tag model (read‑only). */
        Tag: {
            readonly id: number;
            name: string;
            slug?: string;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        Tool: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            readonly description: string;
            /** Format: uri */
            readonly website_url: string;
            /** Format: uri */
            readonly logo: string | null;
            readonly featured: boolean;
            readonly order: number;
            readonly category_name: string;
        };
        /** @description Minimal serializer for the User model (author). */
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    api_v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_v1_blog_list: {
        parameters: {
            query?: {
                /** @description Filter by author ID. */
                author?: number;
                /** @description Filter by category slug (exact match). */
                category?: string;
                /** @description Filter by featured status (true/false). */
                featured?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Filter posts published on or after this date (ISO format). */
                published_after?: string;
                /** @description Filter posts published on or before this date (ISO format). */
                published_before?: string;
                /** @description Filter by tag slug (exact match). */
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostListList"];
                };
            };
        };
    };
    api_v1_blog_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
        };
    };
    api_v1_blog_related_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"][];
                };
            };
        };
    };
    api_v1_contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contact"];
                "application/x-www-form-urlencoded": components["schemas"]["Contact"];
                "multipart/form-data": components["schemas"]["Contact"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    api_v1_knowledge_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Knowledge"];
                };
            };
        };
    };
    api_v1_knowledge_courses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCourseListList"];
                };
            };
        };
    };
    api_v1_knowledge_courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
        };
    };
    api_v1_knowledge_resources_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResourceList"];
                };
            };
        };
    };
    api_v1_knowledge_tools_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tool"][];
                };
            };
        };
    };
    api_v1_projects_list: {
        parameters: {
            query?: {
                category?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                tech?: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectListList"];
                };
            };
        };
    };
    api_v1_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectList"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectList"];
                "multipart/form-data": components["schemas"]["ProjectList"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    api_v1_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    api_v1_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectDetail"];
                "multipart/form-data": components["schemas"]["ProjectDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    api_v1_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectDetail"];
                "multipart/form-data": components["schemas"]["PatchedProjectDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    api_v1_resume_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
}
