// This file is generated by running `npm run gen:types` against the DRF schema.
// It will contain TypeScript definitions for all API endpoints and models.

// Run the command after starting the Django server (e.g. `python manage.py runserver`).

export {}; // placeholder
