# Generated by Django 5.2.6 on 2025-09-07 14:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.TextField(blank=True, max_length=160)),
                ("og_image", models.ImageField(blank=True, upload_to="og_images/")),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                ("secondary_keywords", models.TextField(blank=True)),
                (
                    "readability_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "seo_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("social_media_title", models.CharField(blank=True, max_length=60)),
                (
                    "social_media_description",
                    models.TextField(blank=True, max_length=160),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary with Large Image"),
                        ],
                        default="summary",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="project_thumbnails/")),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("demo_video", models.URLField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("mobile", "Mobile Application"),
                            ("desktop", "Desktop Application"),
                            ("ml", "Machine Learning"),
                            ("data", "Data Science"),
                        ],
                        max_length=10,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=15,
                    ),
                ),
                ("tech_stack", models.ManyToManyField(to="projects.technology")),
            ],
            options={
                "ordering": ["-featured", "-completion_date"],
            },
        ),
    ]
