# Generated by Django 4.2.29 on 2026-04-07 12:32

import apps.seo.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Title tag for search engines (max 70 chars). Leave blank to use post title.', max_length=70, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, help_text='SERP snippet description (max 165 chars). Optimal: 120-160 characters.', max_length=165, verbose_name='Meta Description')),
                ('focus_keyphrase', models.CharField(blank=True, db_index=True, help_text='Primary keyword this post targets for ranking.', max_length=100, verbose_name='Focus Keyphrase')),
                ('secondary_keyphrases', models.JSONField(blank=True, default=list, help_text='Additional target keywords (JSON array format).', verbose_name='Secondary Keyphrases')),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL. Leave blank for default permalink.', verbose_name='Canonical URL')),
                ('robots', models.CharField(choices=[('index,follow', 'Index, Follow'), ('index,nofollow', 'Index, No Follow'), ('noindex,follow', 'No Index, Follow'), ('noindex,nofollow', 'No Index, No Follow')], default='index,follow', help_text='Search engine crawling and indexing directives.', max_length=50, verbose_name='Meta Robots')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing. Defaults to SEO title.', max_length=100, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description. Defaults to meta description.', max_length=300, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended size: 1200×630px for optimal social display.', upload_to=apps.seo.models.get_og_image_upload_path, verbose_name='OG Image')),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter Card title. Defaults to OG title.', max_length=100, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter Card description. Defaults to OG description.', max_length=300, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card image. Defaults to OG image.', upload_to=apps.seo.models.get_og_image_upload_path, verbose_name='Twitter Image')),
                ('schema_type', models.CharField(choices=[('BlogPosting', 'Blog Posting'), ('Article', 'Article'), ('NewsArticle', 'News Article'), ('TechArticle', 'Technical Article'), ('ScholarlyArticle', 'Scholarly Article'), ('FAQPage', 'FAQ Page'), ('HowTo', 'How To'), ('WebPage', 'Web Page')], db_index=True, default='BlogPosting', help_text='Schema.org structured data type for rich snippets.', max_length=20, verbose_name='Schema Type')),
                ('schema_extra', models.JSONField(blank=True, default=dict, help_text='Additional JSON-LD properties not covered by standard fields.', verbose_name='Extra Schema Properties')),
                ('is_cornerstone', models.BooleanField(db_index=True, default=False, help_text='Mark as pillar content for internal linking priority.', verbose_name='Cornerstone Content')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.7, help_text='Priority value from 0.0 to 1.0 (default: 0.7).', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Sitemap Priority')),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', help_text='How frequently content is likely to change.', max_length=10, verbose_name='Change Frequency')),
                ('seo_score', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Aggregated SEO health score (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SEO Score')),
                ('readability_score', models.PositiveSmallIntegerField(blank=True, help_text='Flesch-Kincaid based readability score (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Readability Score')),
                ('seo_score_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed check results: passed, warnings, failures.', verbose_name='Score Breakdown')),
                ('content_hash', models.CharField(blank=True, help_text='sha256 hash for change detection.', max_length=64, verbose_name='Content Hash')),
                ('last_analyzed_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of most recent SEO analysis.', null=True, verbose_name='Last Analyzed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('post', models.OneToOneField(help_text='The associated blog post for these SEO settings.', on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='blog.post', verbose_name='Blog Post')),
            ],
            options={
                'verbose_name': 'Post SEO',
                'verbose_name_plural': 'Post SEO Entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(help_text='Previous URL slug that should redirect.', max_length=255, verbose_name='Old Slug')),
                ('new_slug', models.SlugField(help_text='Target slug to redirect to.', max_length=255, verbose_name='New Slug')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)')], default=301, help_text='301 for permanent moves, 302 for temporary redirects.', verbose_name='Status Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive redirects are ignored by the middleware.', verbose_name='Active')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='blog.post', verbose_name='Blog Post')),
            ],
            options={
                'verbose_name': 'Post Redirect',
                'verbose_name_plural': 'Post Redirects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSEOAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SEO Score')),
                ('readability_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Readability Score')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Complete analysis results for this snapshot.', verbose_name='Score Breakdown')),
                ('triggering_event', models.CharField(choices=[('save', 'Post Save'), ('publish', 'Publication'), ('manual', 'Manual Trigger'), ('bulk', 'Bulk Reanalysis'), ('scheduled', 'Scheduled Task'), ('api', 'API Call')], help_text='What event caused this analysis to run.', max_length=50, verbose_name='Trigger')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('post_seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='seo.postseo', verbose_name='Post SEO')),
            ],
            options={
                'verbose_name': 'SEO Audit Log',
                'verbose_name_plural': 'SEO Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_seo', '-created_at'], name='seo_postseo_post_se_b39727_idx'), models.Index(fields=['triggering_event', 'created_at'], name='seo_postseo_trigger_c8d671_idx'), models.Index(fields=['seo_score', 'created_at'], name='seo_postseo_seo_sco_990d90_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='postseo',
            index=models.Index(fields=['seo_score', 'readability_score'], name='seo_postseo_seo_sco_2eff4f_idx'),
        ),
        migrations.AddIndex(
            model_name='postseo',
            index=models.Index(fields=['last_analyzed_at', 'seo_score'], name='seo_postseo_last_an_50e380_idx'),
        ),
        migrations.AddIndex(
            model_name='postseo',
            index=models.Index(fields=['focus_keyphrase', 'seo_score'], name='seo_postseo_focus_k_6ed094_idx'),
        ),
        migrations.AddIndex(
            model_name='postseo',
            index=models.Index(fields=['is_cornerstone', 'seo_score'], name='seo_postseo_is_corn_362566_idx'),
        ),
        migrations.AddIndex(
            model_name='postseo',
            index=models.Index(fields=['schema_type', 'seo_score'], name='seo_postseo_schema__10b563_idx'),
        ),
        migrations.AddIndex(
            model_name='postredirect',
            index=models.Index(fields=['old_slug', 'is_active'], name='seo_postred_old_slu_331d54_idx'),
        ),
        migrations.AddIndex(
            model_name='postredirect',
            index=models.Index(fields=['post', 'created_at'], name='seo_postred_post_id_ddbd37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postredirect',
            unique_together={('post', 'old_slug')},
        ),
    ]
