# Generated by Django 5.2.6 on 2025-09-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="course_thumbnails/"),
        ),
    ]
